version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: frontend
    restart: always
    networks:
      - appnet
    expose:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - appnet
    expose:
      - "3000"
    ports:
      - "3000:3000"

  proxy:
    image: nginx:stable
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - appnet
    depends_on:
      - frontend
      - backend

networks:
  appnet:
    driver: bridge
