version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - appnet
    expose:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - appnet
    expose:
      - "3000"
    ports:
      - "3000:3000"

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    volumes:
      - ./nginx/nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
