@echo off
echo === RESTAURATION DE TOUS LES FICHIERS VIDES ===

git checkout HEAD -- "src/components/admin/details/EtudiantDetails.vue"
git checkout HEAD -- "src/components/admin/details/ManagementPFPEnCours.vue"
git checkout HEAD -- "src/components/admin/details/ManagementPlacesSafe.vue"
git checkout HEAD -- "src/components/admin/details/OffreDePlac3BA22PFP4.vue"
git checkout HEAD -- "src/components/admin/details/OffreDePlace.vue"
git checkout HEAD -- "src/components/admin/details/PlacesAssigned.vue"
git checkout HEAD -- "src/components/admin/details/UserProfile.vue"
git checkout HEAD -- "src/components/admin/details/VotationLese.vue"
git checkout HEAD -- "src/components/admin/forms/NewUserForm.vue"
git checkout HEAD -- "src/components/admin/forms/PraticienFormateurForm.vue"
git checkout HEAD -- "src/components/admin/items/StatsBox.vue"
git checkout HEAD -- "src/components/admin/lists/AdminSidebar.vue"
git checkout HEAD -- "src/components/common/filters/FilterSidebar.vue"
git checkout HEAD -- "src/components/common/filters/FiltreMap.vue"
git checkout HEAD -- "src/components/social/library/StoryStats.vue"
git checkout HEAD -- "src/components/social/library/TextAreaComponent.vue"
git checkout HEAD -- "src/components/social/library/WebcamCapture.vue"
git checkout HEAD -- "src/components/ui/buttons/ButtonNavbar.vue"
git checkout HEAD -- "src/components/ui/buttons/SwitchColor.vue"
git checkout HEAD -- "src/components/user/details/ChatProfil.vue"
git checkout HEAD -- "src/components/user/details/ProfileInfoAdmin.vue"
git checkout HEAD -- "src/components/user/details/VotationResultProfil.vue"
git checkout HEAD -- "src/components/user/library/ProfileAdminRightSidebar.vue"
git checkout HEAD -- "src/views/admin/institutions/InstitutionDetailsView.vue"
git checkout HEAD -- "src/views/admin/institutions/InstitutionListView.vue"
git checkout HEAD -- "src/views/admin/places/PlaceStatsView.vue"
git checkout HEAD -- "src/views/admin/users/UserListView.vue"
git checkout HEAD -- "src/views/admin/validation/ValidationView.vue"
git checkout HEAD -- "src/views/admin/votations/VotationManagementView.vue"
git checkout HEAD -- "src/views/apps/chat/ChatSidebar.vue"
git checkout HEAD -- "src/views/apps/chat/IndexChat.vue"
git checkout HEAD -- "src/views/apps/events/EventManagementView.vue"
git checkout HEAD -- "src/views/apps/tools/MobileToolsView.vue"
git checkout HEAD -- "src/views/auth/AccessView.vue"
git checkout HEAD -- "src/views/auth/AuthErrorView.vue"
git checkout HEAD -- "src/views/home/MapView.vue"
git checkout HEAD -- "src/views/institutions/InstitutionListView.vue"
git checkout HEAD -- "src/views/social/HashtagView.vue"

echo === RESTAURATION TERMINEE ===
pause
